analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#6a676a'
    - '#c0bfc0'
    - '#00b4cb'
    - '#00739b'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0.504223
  saturation: 0.5
cta: {}
layout_spectrum: 0.598818
name: IvanBucher
opengraph: {}
purpose: []
typography_spectrum: 0.50583
