name: IvanBucher
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49583
title: IvanBucher.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6a676a'
    - '#c0bfc0'
    - '#00b4cb'
    - '#00739b'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
