name: IvanBucher
favicon: null
layout_spectrum: 0.4975
typography_spectrum: 0.49583
title: IvanBucher.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#ffffff'
    - '#ff9400'
    - '#4f2400'
    - '#726155'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
