name: Ivan Bucher
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14525
title: IvanBucher.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8a8a8a'
    - '#e3d9cd'
    - '#535456'
    - '#87c5dc'
  brandStrength: 1
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
